# Generated by Django 5.1.7 on 2025-04-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozy_table", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablebooking",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
